M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Tue 28 Jan 2025 06:24:17 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-28T18:24:17-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T2
X2.126Y-2.126
X2.126Y-3.8583
X5.748Y-2.126
X5.748Y-3.8583
T1
G00X4.2209Y-2.224
M15
G01X4.2209Y-3.7161
M16
G05
M30
